/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnalyticsEventsDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AnalyticsEventsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ShorteningPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "ShorteningRedis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "ShorteningVPC": {
      "type": "sst.aws.Vpc"
    }
    "Urls": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "Users": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Web": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}