/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ShorteningVPC": {
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}

import "sst"
export {}